# Change baseurl before deploy
baseurl = "https://www.shanechang.com"
languageCode = "en-us"
title = "Shane's Personal Blog"
copyright = "Shane Zhang (张欣耕)"
theme = "stack"
disableHugoGeneratorInject = true
enableRobotsTXT = true
# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Define taxonomies to enable series functionality
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

# Output formats for LLMs.txt support
[outputFormats]
[outputFormats.markdown]
name = "markdown"
baseName = "index"
mediaType = "text/markdown"
isPlainText = true

[outputFormats.llms]
baseName = "llms"
isPlainText = true
mediaType = "text/plain"
rel = "alternate"

[outputs]
home = ["HTML", "RSS", "MARKDOWN", "LLMS"]
page = ["HTML", "MARKDOWN", "LLMS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS", "MARKDOWN", "LLMS"]

[pagination]
pagerSize = 10

[services]
[services.googleAnalytics]
id = "G-9RZMBQK5TZ"

[module]
[[module.mounts]]
excludeFiles =  ["playgrounds/*"]
source = 'content'
target = 'content'