# Configure main menu and social menu
[[main]]
identifier = "about"
name = "About Me"
url = "/about/"
weight = 10
[main.params]
icon = "link"

[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 20
[main.params]
icon = "home"

[[main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 30
[main.params]
icon = "search"

[[main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 40
[main.params]
icon = "archives"

[[main]]
identifier = "thinkdifferent"
name = "Think Different"
url = "/think-different/"
weight = 50
[main.params]
icon = "brand-apple"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/zhangxingeng"

[social.params]
icon = "brand-github"

[[social]]
identifier = "x"
name = "x"
url = "https://x.com"

[social.params]
icon = "brand-x"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/zhangxingeng"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "resume"
name = "Resume"
url = "https://shane-zhang-resume-genai.tiiny.site"

[social.params]
icon = "file-cv"
