[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/zhangxingeng"

[social.params]
icon = "brand-github"

[[social]]
identifier = "x"
name = "x"
url = "https://x.com"

[social.params]
icon = "brand-x"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/zhangxingeng"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "resume"
name = "Resume"
url = "https://shane-zhang-resume-genai.tiiny.site"

[social.params]
icon = "file-cv"
