[build]
    publish = "public"
    command = "pnpm install && pnpm run build"

[build.environment]
    HUGO_VERSION = "0.148.2"
    HUGO_EXTENDED = "true"
    NODE_VERSION = "22"
    HUGO_ENV = "production"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"
    [plugins.inputs]
        debug = true
        srcdir = ""

[[headers]]
    for = "/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"

[context.deploy-preview]
    command = "pnpm install && pnpm run build"
