[build]
    publish = "public"
    command = "pnpm install && pnpm run build"

[build.environment]
    HUGO_VERSION = "0.150.0"
    GO_VERSION = "1.25.1"
    HUGO_EXTENDED = "true"
    NODE_VERSION = "22"
    HUGO_ENV = "production"
    NPM_FLAGS = "--version"

# Disable JS bundling to prevent search script corruption
[build.processing]
  [build.processing.js]
    bundle = false
